[package]
name = "axhash-indexmap"
version = "0.1.2"
edition = "2024"
authors = ["Bagus Dwi Harianto robbymangkualam2000@gmail.com"]
license = "MIT"
repository = "https://github.com/robby031/axhash-indexmap"
description = "IndexMap and IndexSet powered by indexmap (SwissTable) and the axhash engine."
keywords = ["indexmap", "ordered", "hashmap", "hash", "performance"]
categories = ["data-structures", "algorithms"]
readme = "README.md"

[features]
default = ["std"]
std = ["indexmap/std"]

[dependencies]
axhash-core = "0.11.0"
indexmap = { version = "2", default-features = false }

[dev-dependencies]
criterion = { version = "0.8.2", features = ["html_reports"] }

[[bench]]
name = "indexmap_comparison"
harness = false
